#!/bin/bash
# ===========================================
# QUICK DEPLOYMENT GUIDE
# ===========================================

echo "📋 News Aggregator - Deployment Checklist"
echo "=========================================="
echo ""
echo "STEP 1: Create a Neon Database (FREE)"
echo "--------------------------------------"
echo "1. Go to: https://neon.tech"
echo "2. Sign up with GitHub"
echo "3. Create a new project (any name)"
echo "4. Copy the connection string"
echo ""
echo "STEP 2: Import to Vercel"
echo "------------------------"
echo "1. Go to: https://vercel.com/new"
echo "2. Import this GitHub repo"
echo "3. Set Root Directory to: apps/web"
echo "4. Add Environment Variables:"
echo "   - DATABASE_URL = (paste Neon connection string)"
echo "   - CRON_SECRET = $(openssl rand -hex 16)"
echo "   - ADMIN_SECRET = $(openssl rand -hex 16)"
echo ""
echo "STEP 3: Run Database Migration"
echo "------------------------------"
echo "After deploying, run this in Neon SQL Editor:"
echo ""
cat migrations/001_processing_queue.sql
echo ""
echo "Also run your existing migrations from infra/postgres/"
echo ""
echo "STEP 4: Add a Feed Source"
echo "-------------------------"
echo "Insert a source and feed into your database:"
echo ""
echo "INSERT INTO sources (domain, name, is_active) VALUES ('techcrunch.com', 'TechCrunch', true);"
echo "INSERT INTO feeds (source_id, url, type) VALUES (1, 'https://techcrunch.com/feed/', 'rss');"
echo ""
echo "Done! Your cron jobs will start collecting articles automatically."
